import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Xtest from './Xtest'
import Link from 'next/link'
import { Navbar } from './Navbar'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Navbar/>
      <main className={styles.main}>
        <div className="text-purple-800 py-8 text-3xl">
         <Link href = "/about">About Page</Link>
          Main
          <div style={{color: '#dde556'}}>
           
            Test
          </div>
         
        </div>
        <div></div>
      </main>

      <footer className={styles.footer}>
        Footer
      </footer>
    </div>
  )
}
